name: C/C++ CUDA CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install CUDA toolkit
    - name: Install CUDA
      run: |
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
        sudo sh -c 'echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/cuda.list'
        sudo apt-get update
        sudo apt-get -y install cuda

    # Compile using nvcc
    - name: Compile CUDA code
      run: nvcc -std=c++17 *.cu *.cpp -o output_executable

    # Optionally, run tests (if applicable)
    - name: Run tests
      run: ./output_executable
